<?php

namespace Monitor;

use Psr\Log\LoggerInterface;

/**
 * Defines common behaviour for disk monitors.
 *
 * @package Monitor
 */
abstract class AbstractDiskMonitor implements Monitor
{
    /**
     * The filesystem directory to monitor.
     *
     * @var string
     */
    protected $directory;

    /**
     * The minimum number of bytes available in the monitored path before a warning is logged.
     *
     * @var int
     */
    protected $threshold = 0;

    /**
     * A logger to which messages generated by the monitor are to be logged.
     *
     * @var \Psr\Log\LoggerInterface
     */
    protected $logger;

    /**
     * @param LoggerInterface $logger
     * @param $threshold
     * @param string $path
     */
    public function __construct(LoggerInterface $logger, $threshold, $path = '/')
    {
        $this->logger = $logger;
        $this->directory = $path;
        $this->threshold = $threshold;
    }
}